server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /menus/**
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**, 
        - id: customer
          uri: http://localhost:8083
          predicates:
            - Path=/customerInfos/**, /myPages/**
        - id: store
          uri: http://localhost:8084
          predicates:
            - Path=/foodCookings/**, 
        - id: rider
          uri: http://localhost:8085
          predicates:
            - Path=/deliveries/**, /deliveryLists/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, /menus/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/customerInfos/**, /myPages/**
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/foodCookings/**, 
        - id: rider
          uri: http://rider:8080
          predicates:
            - Path=/deliveries/**, /deliveryLists/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
